version: '3'

services:
  collabora:
    image: collabora/code:4.0.3.1
    deploy:
      labels:
        traefik.port: 9980
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
      placement:
        constraints: [node.labels.reserved != true]
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - SLEEPFORDEBUGGER=0
      - domain=${NEXTCLOUD_DOMAIN:-cloud\\.domain\\.tld}
      - username=${NEXTCLOUD_USERNAME:-admin}
      - password=${COLLABORA_PASSWORD:-myp@ssw0rd}

networks:
  default:
    external:
      name: traefik-net
