# sudo sysctl -w vm.max_map_count=262144
# echo "vm.max_map_count=262144" > /etc/sysctl.d/99-elasticsearch.conf
# chmod g+rwx esdatadir
# chgrp 1000 esdatadir

version: '3.7'

configs:
  filebeat.yml:
    name: filebeat.yml-${CONFIG_VERSION:-0}
    file: ./configs/filebeat.yml

services:
  elasticsearch:
    image: elasticsearch:6.5.0
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/elasticsearch:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  kibana:
    image: kibana:6.5.0
    deploy:
      labels:
        traefik.port: 5601
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic: ${BASIC_AUTH:?err}
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

  logstash:
    image: logstash:6.5.0
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.0
    user: root
    configs:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - /var/log/:/var/log/:ro
    networks:
      - internal
    deploy:
      mode: global

networks:
  internal:
  traefik:
    external:
      name: traefik-net
