version: '3.7'

services:
  web:
    image: etherpad/etherpad:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/opt/etherpad-lite/var
    deploy:
      labels:
        traefik.port: 9001
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
      placement:
        constraints: [node.labels.reserved != true]

networks:
  default:
    external:
      name: traefik-net
