version: '3.7'

services:
  web:
    image: etherpad/etherpad:latest
    volumes:
        - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/opt/etherpad/var
    deploy:
      labels:
        traefik.port: 9001
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

networks:
  default:
    external:
      name: traefik-net
