version: '3.7'

services:
  web:
    image: usefathom/fathom:latest
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/fathom/fathom.db:/app/fathom.db
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.frontend.headers.customResponseHeaders: "X-Frame-Options: SAMEORIGIN||X-XSS-Protection: 1; mode=block||Strict-Transport-Security: max-age=31536000; includeSubDomains||Referrer-Policy: no-referrer||X-Content-Type-Options: nosniff"
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]

networks:
  default:
    external:
      name: traefik-net
