version: '3.7'

services:
  web:
    image: ghost:2.9.1-alpine
    volumes:
      - ghost:/var/lib/ghost/content:nocopy
    environment:
      url: ${SCHEME:-http}://${DOMAIN:?err}
    deploy:
      labels:
        traefik.port: 2368
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

volumes:
  ghost:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"

networks:
  default:
    external:
      name: traefik-net
