version: '3.7'

services:
  ghost:
    image: ghost:${VERSION:-3.0.3-alpine}
    volumes:
      - ${VOLUME_PATH}ghost:/var/lib/ghost/content
    environment:
      - url=${SCHEME:-http}://${DOMAIN-ghost.localhost}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.rule=Host(`${DOMAIN:-ghost.localhost}`)
      - traefik.http.routers.ghost.tls=${HTTPS:-false}
      - traefik.http.routers.ghost.tls.certresolver=mytlschallenge
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

volumes:
  ghost:

networks:
  default:
    external: true
    name: traefik-net
