version: '3.7'

services:
  web:
    image: huginn/huginn:latest
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/var/lib/mysql
    deploy:
      labels:
        traefik.port: 3000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]

networks:
  default:
    external:
      name: traefik-net
