# apt-get update;apt-get install -y git
# COMPOSER_ALLOW_SUPERUSER=1 composer require mageplaza/magento-2-french-language-pack:dev-master
# php bin/magento setup:static-content:deploy -f fr_FR
# php bin/magento cache:flush

version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=magento
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mysql:/var/lib/mysql
    networks:
      - internal

  magento:
    image: bitnami/magento:2.2.6
    ports:
      - 30001:80
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=myp@ssw0rd
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_HOST=${DOMAIN:?err}
      - MAGENTO_MODE=production
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/magento:/bitnami
    networks:
      - traefik
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
