version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mysql:/var/lib/mysql
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

  mailtrain:
    image: ston3o/mailtrain:1.24.1
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/app/public/grapejs/uploads
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/app/public/mosaico/uploads
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/reports:/app/protected/reports
    deploy:
      labels:
        traefik.port: 3000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  redis:
    image: redis:5.0.2-alpine
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
