version: '3'

services:
  db:
    image: mariadb:10.3.10
    volumes:
      - db:/var/lib/mysql:nocopy
    environment:
      MYSQL_ROOT_PASSWORD: myp@assw0rd
    networks:
      - internal

  matomo:
    image: matomo:3.6.1
    volumes:
      - config:/var/www/html/config:nocopy
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - traefik
      - internal

volumes:
  db:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"
  config:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"

networks:
  internal:
  traefik:
    external:
      name: traefik-net
