# mkdir config data db plugins && chown -R 2000:2000 config plugins data
# Add SMTP configuration on Notifications -> Email
# Change language on General -> Language (only first two fields)

version: "3.7"

services:
  db:
    image: postgres:9.4-alpine
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=mattermost
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  app:
    image: mattermost/mattermost-prod-app:5.9.0
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/mattermost/data
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/config:/mattermost/config
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/plugins:/mattermost/plugins
    environment:
      - MM_USERNAME=mattermost
      - MM_PASSWORD=myp@ssw0rd
      - MM_DBNAME=mattermost
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  web:
    image: mattermost/mattermost-prod-web:5.9.0
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal
      - traefik

networks:
  internal:
  traefik:
    external:
      name: traefik-net
