version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2018-10-25T01-27-03Z
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - /mnt/data:/data
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname==master]

secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
