version: '3.7'

configs:
  prometheus.yml:
    name: prometheus.yml-${CONFIG_VERSION:-0}
    file: ./configs/prometheus.yml
  alert.rules.yml:
    name: alert.rules-${CONFIG_VERSION:-0}
    file: ./configs/alert.rules.yml
  alertmanager.yml:
    name: alertmanager.yml-${CONFIG_VERSION:-0}
    file: ./configs/alertmanager.yml

services:
  prometheus:
    image: prom/prometheus:v2.4.3
    ports:
      - 9090:9090
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alert.rules.yml
        target: /etc/prometheus/alert.rules.yml
    networks:
      - internal
      - traefik

  grafana:
    image: grafana/grafana:5.3.2
    user: root
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana:nocopy
    networks:
      - internal

  cadvisor:
    image: google/cadvisor:v0.31.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    networks:
      - internal
      
  node-exporter:
    image: prom/node-exporter:v0.16.0
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/nodename
    hostname: "{{.Node.Hostname}}"
    environment:
      HOST_HOSTNAME: /etc/hostname
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    deploy:
      mode: global
    networks:
      - internal

  alertmanager:
    image: prom/alertmanager:v0.15.2
    ports:
      - 9093:9093
    command: --config.file=/etc/alertmanager/alertmanager.yml
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    networks:
      - internal

volumes:
  grafana:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"

networks:
  internal:
  traefik:
    external:
      name: traefik-net
