version: '3.7'

configs:
  prometheus.yml:
    name: prometheus.yml-${CONFIG_VERSION:-0}
    file: ./configs/prometheus.yml
  alert.rules.yml:
    name: alert.rules-${CONFIG_VERSION:-0}
    file: ./configs/alert.rules.yml
  alertmanager.yml:
    name: alertmanager.yml-${CONFIG_VERSION:-0}
    file: ./configs/alertmanager.yml
  blackbox.yml:
    name: blackbox.yml-${CONFIG_VERSION:-0}
    file: ./configs/blackbox.yml

services:
  prometheus:
    image: prom/prometheus:v2.8.0
    user: root
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alert.rules.yml
        target: /etc/prometheus/alert.rules.yml
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/prometheus:/prometheus
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        traefik.port: 9090
        traefik.frontend.rule: Host:${DOMAIN_PROMETHEUS:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
        traefik.frontend.auth.basic.users: ${BASIC_AUTH:?err}
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 350M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal
      - traefik

  grafana:
    image: grafana/grafana:6.0.1
    user: root
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/grafana:/var/lib/grafana
    deploy:
      labels:
        traefik.port: 3000
        traefik.frontend.rule: Host:${DOMAIN_GRAFANA:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - internal
      
  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/nodename
    environment:
      - NODE_ID={{.Node.ID}}
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - internal

  alertmanager:
    image: prom/alertmanager:v0.16.1
    command: --config.file=/etc/alertmanager/alertmanager.yml
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.14.0
    command: --config.file=/config/blackbox.yml
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal
      - traefik
    configs:
      - source: blackbox.yml
        target: /config/blackbox.yml

networks:
  internal:
  traefik:
    external:
      name: traefik-net
