version: '3.7'

services:
  nextcloud:
    image: nextcloud:${VERSION:-17.0.1}
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}nextcloud:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN:-nextcloud.localhost}`)
      - traefik.http.routers.nextcloud.tls=${HTTPS:-false}
      - traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge
      - traefik.http.routers.nextcloud.middlewares=nextcloud-mid1,nextcloud-mid2
      - traefik.http.middlewares.nextcloud-mid1.headers.framedeny=true
      - traefik.http.middlewares.nextcloud-mid1.headers.stsSeconds=31536000
      - traefik.http.middlewares.nextcloud-mid1.headers.sslredirect=${HTTPS:-false}
      - traefik.http.middlewares.nextcloud-mid1.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nextcloud-mid2.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-mid2.redirectregex.replacement=https://$$1/remote.php/dav/
      - traefik.http.middlewares.nextcloud-mid2.redirectregex.permanent=true
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  nextcloud:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
