version: '3'

services:
  nextcloud:
    image: nextcloud:14.0.4
    volumes:
      - nextcloud:/var/www/html:nocopy
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"

volumes:
  nextcloud:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"

networks:
  default:
    external:
      name: traefik-net
