# php occ --no-warnings config:system:set trusted_domains 1 --value="nginx"
# php occ --no-warnings app:install onlyoffice
# php occ --no-warnings config:system:set onlyoffice DocumentServerUrl --value="/ds-vpath/"
# php occ --no-warnings config:system:set onlyoffice DocumentServerInternalUrl --value="http://onlyoffice-document-server/"
# php occ --no-warnings config:system:set onlyoffice StorageUrl --value="http://nginx/"

version: '3.7'

services:
  nginx:
    image: ston3o/onlyoffice-proxy:latest
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.frontend.headers.customResponseHeaders: "Strict-Transport-Security: max-age=31536000;||Referrer-Policy: no-referrer;"
        traefik.frontend.redirect.permanent: 'true'
        traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
        traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      placement:
        constraints: [node.labels.reserved != true]
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/nextcloud:/var/www/html
    networks:
      - traefik
      - internal

  nextcloud:
    image: nextcloud:16.0.4-fpm
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/nextcloud:/var/www/html
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  onlyoffice-document-server:
    image: onlyoffice/documentserver:5.4.0.21
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
