version: '3'

services:
  owncloud:
    image: owncloud/server:10.0.10
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN:?err}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=root
      - OWNCLOUD_DB_PASSWORD=myp@ssw0rd
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=admin
      # - OWNCLOUD_ADMIN_PASSWORD=${PASSWORD:?err}
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/owncloud:/mnt/data
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.10
    environment:
      MYSQL_ROOT_PASSWORD: myp@ssw0rd
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mariadb:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
