version: "3.3"

services:
  peertube:
    image: chocobozzz/peertube:v1.2.1-stretch
    environment:
      - PEERTUBE_DB_USERNAME=postgres
      - PEERTUBE_DB_PASSWORD=myp@ssw0rd
      - PEERTUBE_WEBSERVER_HOSTNAME=${DOMAIN:?err}
      - PEERTUBE_WEBSERVER_PORT=443
      - PEERTUBE_WEBSERVER_HTTPS=true
      - PEERTUBE_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@domain.tld}
      - PEERTUBE_SMTP_USERNAME=${SMTP_USERNAME}
      - PEERTUBE_SMTP_PASSWORD=${SMTP_PASSWORD}
      - PEERTUBE_SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - PEERTUBE_SMTP_PORT=${SMTP_PORT:-25}
      - PEERTUBE_SMTP_FROM=${SMTP_FROM}
      - PEERTUBE_SMTP_TLS=${SMTP_TLS:-true}
      - PEERTUBE_SMTP_DISABLE_STARTTLS=false
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/data
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/config:/config
    deploy:
      labels:
        traefik.port: 9000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=peertube
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/postgres:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:4-alpine
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
