version: '3.7'

services:
  agent:
    image: portainer/agent:1.5.1
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
    networks:
      - agent_network

  portainer:
    image: portainer/portainer:1.23.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - ${VOLUME_PATH}portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${DOMAIN:-portainer.localhost}`)
      - traefik.http.routers.portainer.tls=${HTTPS:-false}
      - traefik.http.routers.portainer.tls.certresolver=mytlschallenge
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - agent_network
      - traefik

volumes:
  portainer:

networks:
  traefik:
    external: true
    name: traefik-net
  agent_network:
    driver: overlay
    attachable: true
