version: '3.7'

services:
  agent:
    image: portainer/agent:1.2.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
    networks:
      - agent_network

  portainer:
    image: portainer/portainer:1.20.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/portainer:/data
    deploy:
      labels:
        traefik.port: 9000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - agent_network
      - traefik

networks:
  traefik:
    external:
      name: traefik-net
  agent_network:
    driver: overlay
    attachable: true
