version: '3.7'

services:
  web:
    image: rocketchat/rocket.chat:0.74.3
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/uploads:/app/uploads
    environment:
      - ROOT_URL=${SCHEME:-http}://${DOMAIN:?err}
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    deploy:
      labels:
        traefik.port: 3000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      placement:
        constraints: [node.labels.reserved != true]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mongo:/data/db
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
