# docker exec -it <container_web_name> sentry upgrade

version: '3.4'

x-defaults: &defaults
  image: sentry:9.0.0
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_EMAIL_HOST: smtp
    SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
  volumes:
    - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/sentry:/var/lib/sentry/files

services:
  memcached:
    image: memcached:1.5-alpine
    networks:
      - internal

  redis:
    image: redis:3.2-alpine
    networks:
      - internal

  postgres:
    image: postgres:9.5
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/postgres:/var/lib/postgresql/data
    networks:
      - internal

  web:
    <<: *defaults
    deploy:
      labels:
        traefik.port: 9000
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - traefik
      - internal

  cron:
    <<: *defaults
    command: run cron
    networks:
      - internal

  worker:
    <<: *defaults
    command: run worker
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
