version: "3.3"

services:
  traefik:
    image: traefik:1.7.12
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.toml:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  default:
    external:
      name: traefik-net
