version: '3.7'

services:
  traefik:
    image: traefik:${VERSION:-v2.0.6}
    command:
      # - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=traefik-net
      - --providers.docker.exposedByDefault=false
      - --entrypoints.http.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  letsencrypt:

networks:
  default:
    external: true
    name: traefik-net
