version: '3.7'

services:
  web:
    image: wallabag/wallabag:2.3.8
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/var/www/wallabag/data
    environment:
      SYMFONY__ENV__DOMAIN_NAME: ${SCHEME:-http}://${DOMAIN:?err}
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]

networks:
  default:
    external:
      name: traefik-net
