version: '3.7'

services:
  web:
    image: wekanteam/wekan:v2.01
    environment:
      - MONGO_URL=mongodb://mongo
      - VIRTUAL_HOST=${DOMAIN}
      - ROOT_URL=${SCHEME:-http}://${DOMAIN:?err}
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    volumes:
      - mongo:/data/db:nocopy
    networks:
      - internal

volumes:
  mongo:
    driver: nfs
    driver_opts:
      share: ${NFS_SERVER:?err}:/mnt/data
      create: "true"

networks:
  internal:
  traefik:
    external:
      name: traefik-net
