version: '3.7'

services:
  web:
    image: wekanteam/wekan:v2.01
    environment:
      - MONGO_URL=mongodb://mongo
      - VIRTUAL_HOST=${DOMAIN}
      - ROOT_URL=${SCHEME:-http}://${DOMAIN:?err}
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:4.0.3
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mongo:/data/db
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
