# cp -r /tmp/YetiForceCRM/. /var/www/html
# Change /var/www/html/config/Main.php : public static $site_URL = 'https://site.fr/';

version: '3.7'

services:
  web:
    image: efero/yetiforcecrm:5.1.0
    environment:
      DB_HOST_NAME: mysql
      DATABASE_NAME: yetiforce
      DB_USER_NAME: yetiforce
      DB_PASSWORD: myp@ssw0rd
      DB_TYPE: mysql
      DB_TCP_PORT: 3306
      DB_MANAGER: MysqlManager 
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/var/www/html
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: myp@ssw0rd
      MYSQL_DATABASE: yetiforce
      MYSQL_USER: yetiforce
      MYSQL_PASSWORD: myp@ssw0rd
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
