filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog*"]

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/traefik/*.json
    json.keys_under_root: true
    json.add_error_key: true
    fields_under_root: true
    fields:
      tags: ['beats','json','traefik']

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.dashboards:
  enabled: true

setup.kibana:
  host: "kibana:5601"
