debug = false
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]

[acme]
email = "contact@ethibox.fr"
storage = "acme.json"
acmeLogging = true
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  watch = true
  swarmmode = true
  exposedByDefault = false

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
