debug = false
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "contact@ston3o.me"
storage = "acme.json"
acmeLogging = true
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  watch = true
  swarmmode = true
  exposedByDefault = false

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"

[accessLog]
  filePath = "/var/log/traefik/access.log.json"
  format = "json"
